"""SQLAlchemy ORM models."""
from __future__ import annotations

import datetime as dt
import json
from enum import Enum

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


def _utcnow() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


def _as_utc(value: "dt.datetime | None") -> "dt.datetime | None":
    """Coerce a possibly-naive datetime (SQLite hands back naive) to aware UTC.

    Licence expiry is compared against :func:`_utcnow` (aware), so a naive value
    read back from the DB must be treated as UTC rather than raising on compare.
    """
    if value is None:
        return None
    if value.tzinfo is None:
        return value.replace(tzinfo=dt.timezone.utc)
    return value.astimezone(dt.timezone.utc)


class OrderSide(str, Enum):
    buy = "buy"
    sell = "sell"


class TradeStatus(str, Enum):
    pending = "pending"  # limit order resting on the book, not yet filled
    open = "open"
    closed = "closed"
    canceled = "canceled"


class OrderType(str, Enum):
    market = "market"
    limit = "limit"


class UserRole(str, Enum):
    admin = "admin"
    user = "user"


class LicenseStatus(str, Enum):
    pending = "pending"    # signed up, waiting for the admin to grant a licence
    active = "active"      # licensed — may configure keys and trade
    revoked = "revoked"    # licence withdrawn by the admin


class LicenseKeyStatus(str, Enum):
    unused = "unused"      # generated by an admin, not yet redeemed
    redeemed = "redeemed"  # a user activated their account with it (one-time)
    revoked = "revoked"    # admin invalidated it before it was redeemed


class User(Base):
    """A registered account. Each user brings their OWN exchange/AI keys.

    Secrets (Binance + AI keys) are stored ENCRYPTED at rest (Fernet, key
    derived from SECRET_KEY) — never in plaintext. Access to trading is gated by
    ``license_status``: users are ``pending`` until the admin grants a licence.
    """

    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    # Optional handle a client can log in with instead of their email. Unique
    # (case-insensitive enforced at the API layer); NULL for legacy accounts.
    username: Mapped[str | None] = mapped_column(
        String(64), unique=True, index=True, nullable=True
    )
    password_hash: Mapped[str] = mapped_column(String(255))
    role: Mapped[str] = mapped_column(String(8), default=UserRole.user.value)
    license_status: Mapped[str] = mapped_column(
        String(12), default=LicenseStatus.pending.value, index=True
    )
    webhook_token: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    binance_api_key_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    binance_api_secret_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    binance_testnet: Mapped[bool] = mapped_column(Integer, default=1)
    ai_api_key_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    ai_base_url: Mapped[str | None] = mapped_column(String(255), nullable=True)
    ai_model: Mapped[str | None] = mapped_column(String(64), nullable=True)
    ai_style: Mapped[str | None] = mapped_column(String(16), nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    licensed_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # When set, the licence AUTO-EXPIRES at this instant (time-limited plan sold
    # via a licence key with a day count). NULL = no expiry (lifetime / admin).
    license_expires_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    @property
    def license_expired(self) -> bool:
        """True only for a time-limited licence that has passed its expiry."""
        exp = _as_utc(self.license_expires_at)
        return exp is not None and _utcnow() >= exp

    @property
    def license_active(self) -> bool:
        """Licensed AND not expired — the single source of truth for access."""
        return (
            self.license_status == LicenseStatus.active.value
            and not self.license_expired
        )

    @property
    def license_days_left(self) -> int | None:
        """Whole days until expiry (ceil), 0 if past, None if no expiry set."""
        exp = _as_utc(self.license_expires_at)
        if exp is None:
            return None
        secs = int((exp - _utcnow()).total_seconds())
        return 0 if secs <= 0 else (secs + 86399) // 86400


class Trade(Base):
    """A single executed trade / position lifecycle record."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)
    symbol: Mapped[str] = mapped_column(String(32), index=True)
    side: Mapped[str] = mapped_column(String(8))
    amount: Mapped[float] = mapped_column(Float)
    entry_price: Mapped[float] = mapped_column(Float)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    take_profit: Mapped[float | None] = mapped_column(Float, nullable=True)
    status: Mapped[str] = mapped_column(String(12), default=TradeStatus.open.value, index=True)
    pnl: Mapped[float] = mapped_column(Float, default=0.0)
    order_type: Mapped[str] = mapped_column(String(8), default="market")
    limit_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    mode: Mapped[str] = mapped_column(String(8), default="paper")
    source: Mapped[str] = mapped_column(String(24), default="manual")
    exchange_order_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    stop_order_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    opened_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    closed_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class SignalLog(Base):
    """Audit log of incoming signals (TradingView webhooks, strategy triggers)."""

    __tablename__ = "signal_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)
    source: Mapped[str] = mapped_column(String(24), default="tradingview")
    symbol: Mapped[str | None] = mapped_column(String(32), nullable=True)
    action: Mapped[str | None] = mapped_column(String(16), nullable=True)
    raw: Mapped[str] = mapped_column(Text)
    accepted: Mapped[int] = mapped_column(Integer, default=0)  # 0/1 as bool
    message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    @property
    def confidence(self) -> float | None:
        """Confidence parsed out of ``raw`` for analyzer rows, else None.

        Analyzer rows store the full analysis JSON (which carries a real
        confidence); TradingView payloads usually don't, so this returns None
        rather than inventing a number — honouring the nothing-fake rule.
        """
        try:
            data = json.loads(self.raw)
        except Exception:
            return None
        val = data.get("confidence") if isinstance(data, dict) else None
        if isinstance(val, bool) or not isinstance(val, (int, float)):
            return None
        return float(val)


class PriceAlert(Base):
    """A user-defined price alert: notify when a symbol crosses a level.

    Deterministic and real — it fires only when the LIVE market price actually
    crosses the level, and fires once (``status`` flips to ``triggered``) so it
    never spams. No price is ever fabricated: if the price can't be read on a
    tick the alert is simply left armed for the next one.
    """

    __tablename__ = "price_alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int | None] = mapped_column(Integer, index=True, nullable=True)
    symbol: Mapped[str] = mapped_column(String(32), index=True)
    condition: Mapped[str] = mapped_column(String(8))  # "above" | "below"
    price: Mapped[float] = mapped_column(Float)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(12), default="armed", index=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    triggered_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    triggered_price: Mapped[float | None] = mapped_column(Float, nullable=True)


class KeyValue(Base):
    """Simple persisted key/value store for runtime state.

    Used to survive restarts for things that would otherwise live only in
    memory: overridden settings and the paper-trading wallet balance. Values are
    stored as JSON text.
    """

    __tablename__ = "kv_store"

    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    value: Mapped[str] = mapped_column(Text)
    updated_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, onupdate=_utcnow
    )


class LicenseKey(Base):
    """A one-time licence key an admin generates for self-service activation.

    The plaintext key is shown ONCE at generation and NEVER stored — we keep only
    a SHA-256 ``key_hash`` (so a database leak cannot reveal usable keys) plus a
    short ``key_prefix`` for the admin to recognise the row. Redeeming an unused
    key flips a *pending* user straight to an active licence, so no manual
    per-user approval is needed. A key can be redeemed exactly once.
    """

    __tablename__ = "license_keys"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    key_hash: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    key_prefix: Mapped[str] = mapped_column(String(16))  # display only, e.g. "TT-Ab3x"
    label: Mapped[str | None] = mapped_column(String(120), nullable=True)
    # How many days of access the key grants when redeemed. NULL = lifetime.
    duration_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    status: Mapped[str] = mapped_column(
        String(12), default=LicenseKeyStatus.unused.value, index=True
    )
    created_by: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[dt.datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow
    )
    redeemed_by: Mapped[int | None] = mapped_column(Integer, nullable=True)
    redeemed_at: Mapped[dt.datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
